# Generated by Django 4.0.6 on 2022-08-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vg_frontend', '0002_alter_playthrough_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playthrough',
            old_name='title',
            new_name='game',
        ),
        migrations.AddField(
            model_name='playthrough',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playthrough',
            name='playthrough_title',
            field=models.CharField(default='Standard', max_length=200),
        ),
    ]
