# Generated by Django 4.0.6 on 2022-08-21 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vg_frontend', '0004_playthrough_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playthrough',
            name='owner',
        ),
        migrations.AddField(
            model_name='playthrough',
            name='owner',
            field=models.ManyToManyField(related_name='playthroughs', to=settings.AUTH_USER_MODEL),
        ),
    ]
