# Generated by Django 4.0.6 on 2022-08-21 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vg_frontend', '0006_remove_playthrough_owner_playthrough_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playthrough',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
