# Generated by Django 4.0.6 on 2022-08-22 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vg_frontend', '0007_alter_playthrough_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='playthrough',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
