# Generated by Django 4.0.6 on 2022-08-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vg_frontend', '0008_playthrough_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playthrough',
            name='game',
        ),
    ]
