# Generated by Django 4.0.6 on 2022-08-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vg_frontend', '0012_playthrough_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='playthrough',
            name='nothing',
            field=models.CharField(default='', max_length=100),
        ),
    ]
