# Generated by Django 4.0.6 on 2022-08-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vg_frontend', '0013_playthrough_nothing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playthrough',
            name='nothing',
        ),
    ]
