# Generated by Django 4.0.6 on 2022-08-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vg_api', '0002_game_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='temp', max_length=1000),
            preserve_default=False,
        ),
    ]
