# Generated by Django 4.0.6 on 2022-08-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vg_api', '0003_alter_game_options_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
